import './global.css'

export const metadata = {
  title: 'JacareDev',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="pt-br">
      <body>{children}</body>
    </html>
  )
}
